app = "tempoforge-web"
primary_region = "cdg"

[build]
  dockerfile = "client/tempoforge-web/Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = "app"

  [[http_service.checks]]
    type = "http"
    grace_period = "10s"
    interval = "5s"
    timeout = "2s"
    method = "GET"
    path = "/"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
