# fly.toml app configuration file generated for tempoforge-api on 2025-09-18T23:51:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tempoforge-api'
primary_region = 'cdg'

[build]
  dockerfile = "server/TempoForge.Api/Dockerfile"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

    [[http_service.checks]]
     grace_period = "10s"
     interval = "5s"
     timeout = "2s"
     method = "GET"
     path = "/health"
     
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
