name: Build, Test & Deploy

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build TempoForge.sln --configuration Release --no-restore

      - name: Backend tests
        env:
          TESTCONTAINERS_RYUK_DISABLED: "true"
        run: dotnet test TempoForge.sln --no-build --verbosity normal

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Frontend tests
        working-directory: client/tempoforge-web
        run: |
          corepack enable
          pnpm install --frozen-lockfile
          pnpm test -- --ci

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy API
        run: |
          cd server/TempoForge.Api
          flyctl deploy --app tempoforge-api --remote-only

      - name: Deploy Web
        run: |
          cd client/tempoforge-web
          flyctl deploy --app tempoforge-web --remote-only
