name: Build & Test (.NET + Testcontainers)

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build TempoForge.sln --configuration Release --no-restore

      - name: Run tests
        env:
          DOTNET_RUNNING_IN_CONTAINER: "false"
          TESTCONTAINERS_RYUK_DISABLED: "true"
        run: dotnet test TempoForge.sln --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.build-test.result == 'success'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy API
        run: |
          cd server/TempoForge.Api
          flyctl deploy --app tempoforge-api --remote-only

      - name: Deploy Web
        run: |
          cd client/tempoforge-web
          flyctl deploy --app tempoforge-web --remote-only
